### ISSUE TITLE
In the 1.10.2 mod file betterleaves is included; mcmod.info is default.

### ISSUE THREAD

**Issue by QuImUfu** [UpcraftLP/Hardcore-Survival-1.10#2]
1. Both hardcoresurvival and betterleaves are included in the 1.10.2 mod .jar file from GitHub
2. You are using the exemplemod  mcmod.info.
   Better mcmod.info:

``` json
[
{
  "modid": "hardcoresurvival",
  "name": "Harcore Survival Mod",
  "description": "Small mod making Minecrafts earlygame more realistic and difficult.",
  "version": "${version}",
  "mcversion": "${mcversion}",
  "url": "http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2704915",
  "updateUrl": "http://mods.curse.com/mc-mods/minecraft/247029-hardcore-survival-mod",
  "authorList": ["UpcraftLP"],
  "credits": "",
  "screenshots": [],
  "dependencies": []
}
]
```

**Comment by UpcraftLP** [comment]
1. that was a fault with my workspace caused by the name change, fixed it.
2. the mcmod.info is generated at runtime, look [here](https://github.com/UpcraftLP/Hardcore-Survival-1.10/blob/master/src/main/java/mod/upcraftlp/hardcoresurvival/Main.java#L34-L47). Anyways, I remvoed the example file.

**Comment by QuImUfu** [comment]
There is a small problem with you mod generating this at runtime, MultiMC, a custom Launcher with easy mod installation uses this file to get mod version and name and to provide a convenient link to the mods page without starting Minecraft at all. (i think some other utilities use that file as well)  
Maybe generating it build time would be a better/more logical option?  
This is also true because if you generate it at runtime, you generate it every startup without any reason.

**Comment by UpcraftLP** [comment]
re-implemented it, will be included in the next release.
